Refactoring: Code
anpolol/GraphGenerator pull request #9
Opened 2023-03-15 11:47 UTC by anpolol

Solving Issue #1.

Added dockstrings, types, renames vars

2023-03-15 12:59 UTC, aPovidlo requested changes
Думаю, что еще можно добавить пару простых тестов для `bter` и `generator`, для отслеживания неполадок при изменениях кода

2023-03-15 12:59 UTC, aPovidlo commented on core/bter.py
>          # со степенями 1 надо отдельно разбираться
Смущает, что докстринги на английском, а внутрение комментарии на русском. Может быть стоит отказаться от них, либо если они необходимы, то перевести.

2023-03-15 12:59 UTC, aPovidlo commented on core/bter.py
>                      #   print('exc',deg,i,len(communities),len(communities[i]),deg - ro_r*(len(comm)-1))
Cтоит убрать закомментированные `print` на главной ветки, т.к. выглядит не солидно

2023-03-15 12:59 UTC, aPovidlo commented on core/bter.py
>      def xke(self, l: int, m: int) -> List[int]:
А что значит `xke`?

2023-03-15 12:59 UTC, aPovidlo commented on core/bter.py
> +    def build_graph(self) -> nx.Graph:
В целом получается перегруженная функция, которую внутри можно поделить еще на другие функции для более общей читаймости кода.

2023-03-15 12:59 UTC, aPovidlo commented on core/bter.py
>              # разбиваем на общества
Выше писал про разбиение функции, это один из примеров. Разитие на общества можно вынести в доп. функцию в рамках этого класса. Если функция внутрення, то можно воспользоваться статической функцией.

2023-03-15 12:59 UTC, aPovidlo commented on core/bter.py
>              list(range(len(list(filter(lambda x: x > 0, sorted(self.degrees))))))
Трудно читаемый код. Остальные `lambda` выражение тоже, и кмк их засилие тоже усложняют прочтение. По возможности их лучше бы не использовать.

2023-03-15 12:59 UTC, aPovidlo commented on core/bter.py
>      def xke(self, l: int, m: int) -> List[int]:
И не совсем понятно, почему нужно вводить новую функцию, которая дублирует функционал `range()`

2023-03-15 12:59 UTC, aPovidlo commented on core/generator.py
>          :return: (({int: int}, {int: int}, {int: int}))
Думаю, что словесное пояснение возвращаемому значению тоже стоит написать. И не совсем понятно почему двойные скобки `(( ... ))`

2023-03-15 12:59 UTC, aPovidlo commented on core/generator.py
>          dict_of_parameters["connected components"] = nx.number_connected_components(
Ключ словаря с маленькой буквы, а другие с большой

2023-03-15 12:59 UTC, aPovidlo commented on core/generator.py
>              # print(p)
Закомментированный `print`

2023-03-15 12:59 UTC, aPovidlo commented on core/generator.py
>          print("--------------------")
Думаю, что тут стоит подумать и выводить через `logging` или превратить в одну строку через тройные кавычки и спец. символы, чем нежели использовать `print`-ы в кадой строчке

2023-03-20 16:14 UTC, anpolol commented on core/bter.py
>          # со степенями 1 надо отдельно разбираться
исправила, часть удалила

2023-03-20 16:14 UTC, anpolol commented on core/bter.py
>                      #   print('exc',deg,i,len(communities),len(communities[i]),deg - ro_r*(len(comm)-1))
почистила

2023-03-20 16:14 UTC, anpolol commented on core/bter.py
>      def xke(self, l: int, m: int) -> List[int]:
убрала, действительно лишнее

2023-03-20 16:14 UTC, anpolol commented on core/bter.py
> +    def build_graph(self) -> nx.Graph:
исправлю в следующей итерации исправлений

2023-03-20 16:15 UTC, anpolol commented on core/generator.py
>          :return: (({int: int}, {int: int}, {int: int}))
добавила

2023-03-20 16:15 UTC, anpolol commented on core/generator.py
>          print("--------------------")
исправила

2023-03-20 16:16 UTC, aPovidlo commented on .github/workflows/mirror_repo_to_gitlab.yml
> +      GITLAB_URL: https://gitlab.actcognitive.org/anpolol/GraphGenerator
Ненужные изменения конфига, которые вызовут проблемы с зеркалированием

2023-03-20 16:22 UTC, aPovidlo commented on core/generator.py
>          :return: (({int: int}, {int: int}, {int: int}))
Да, но все еще не понимаю зачем там двойные скобки?

2023-03-20 16:34 UTC, aPovidlo requested changes

2023-03-20 16:34 UTC, aPovidlo commented on core/generator.py
>      def xk(self, min_d: int, max_d: int) -> List[int]:
Еще одна функция, которая дублирует функционал `range()`

2023-03-20 16:34 UTC, aPovidlo commented on core/tuning_parameters.py
> +                    np.save(
Может быть сделать этот выбор опциональным, чтобы не спамить файлами в директорию? Или они нужны?

2023-03-20 16:34 UTC, aPovidlo commented on tutorials/example_generate_graph.py
> +model = Model(
Позже запущу пример, чтобы проверить и отпишусь в этом комментарии

2023-03-21 13:55 UTC, anpolol commented on core/tuning_parameters.py
> +                    np.save(
по идее суть этого скрипта - создать и сохранить бенчмарк чтоб потом его в своих проектах использовать

2023-03-29 13:05 UTC, aPovidlo requested changes

2023-03-29 13:05 UTC, aPovidlo commented on core/generator.py
> +from community import community_louvain
Возникает ошибка
```
ImportError: cannot import name 'community_louvain' from 'community' (C:\Users\andre\Documents\GitHub\GraphGenerator\venv\lib\site-packages\community\__init__.py)
```

В документации `community` везде пишут, что нужно:
```
import community as community_louvain
```

Можешь перепроверить?

2023-03-29 13:05 UTC, aPovidlo commented on core/generator.py
> +from community import community_louvain
Разобрался, возможно неверный модуль в requirements.txt стоит. Необходимо заменить `community==1.0.0b1` на `python-louvain==_нужная версия_`

2023-03-29 13:05 UTC, aPovidlo commented on core/generator.py
> +            "\nNumber of classes:{} \nEtta:{} \nro:{} \nRatio of neigbors with same label:{} "
Не хватает пробелов после двоеточий. Может быть еще стоит по-мимо статистики выводить графически и сам граф?

2023-03-29 13:05 UTC, aPovidlo commented on core/tuning_parameters.py
> +from hyperopt import STATUS_OK, Trials, atpe, fmin, hp, tpe
Отсутствует информация в `requirements.txt` об необходимости установки данного модуля

2023-03-29 13:05 UTC, aPovidlo commented on core/tuning_parameters.py
> +from hyperopt import STATUS_OK, Trials, atpe, fmin, hp, tpe
Еще если поставить только hyperopt, то он вываливается с этим:
```
ImportError: You must install lightgbm and sklearn in order to use the ATPE algorithm. Please run `pip install lightgbm scikit-learn` and try again. These are not built in dependencies of hyperopt.
```

2023-03-29 13:05 UTC, aPovidlo commented on examples/example_parameters_tuning.py
> +# last value should be equal 1 as it is responsble for number of connected components
responsble -> responsible

2023-03-29 13:05 UTC, aPovidlo commented on examples/example_parameters_tuning.py
> +# label assortativity, feature assortativity, clustering coefficient, average length of shortest paths, average degree,
shortest -> the shortest

2023-03-29 13:05 UTC, aPovidlo commented on examples/example_generate_graph.py
> +    1.1  # dispertion of each cluster attrbutes' possible values are in range [0.8,1.31)
наверное, опечатка в dispertion?

2023-03-29 13:05 UTC, aPovidlo commented on examples/example_generate_graph.py
> +    1.1  # dispertion of each cluster attrbutes' possible values are in range [0.8,1.31)
и attrbutes -> attributes

2023-04-05 10:26 UTC, anpolol commented on core/generator.py
> +from community import community_louvain
исправила reqirments и на другое замечание тоже

2023-04-05 10:26 UTC, anpolol commented on core/generator.py
> +            "\nNumber of classes:{} \nEtta:{} \nro:{} \nRatio of neigbors with same label:{} "
добавила рисование отдельной функцией

2023-04-05 11:14 UTC, aPovidlo commented on core/generator.py
> +from community import community_louvain
@anpolol Не хватает `lightgbm`

2023-04-05 11:40 UTC, aPovidlo requested changes

2023-04-05 11:40 UTC, aPovidlo commented on examples/example_generate_graph.py
> +
Лучше сделать внутри обертку из `if __name__ == '__main__'` и вынести пример как отдельную функцию. Вот [пример](https://github.com/aimclub/FEDOT/blob/master/examples/simple/classification/api_classification.py) реализации

2023-04-05 11:40 UTC, aPovidlo commented on examples/example_parameters_tuning.py
> +# Here we should set up graph characteristics which constructed graph should have in the following order:
Тот же комментарий, что и выше про обертку. Это описание можно добавить как докстринг к функции

2023-04-05 11:40 UTC, aPovidlo commented on tests/test_bter.py
> +def test_bter_degrees():
Хотелось бы видеть тестирование не только класса в целом, но и вложенных внутри функций на анализ их работоспособности

2023-04-05 11:40 UTC, aPovidlo commented on tests/test_bter.py
> +        sum += 1 / (pow(i, 2.0))
Этот цикл можно сократить до `sum(1 / (pow(i, 2.0) for i in range(min_d, max_d + 1))` вроде как

2023-04-05 11:40 UTC, aPovidlo commented on tests/test_bter.py
> +    model = BTER(
Дописать бы названия недостающих передаваемых аргументов в `BTER()`

2023-04-05 11:40 UTC, aPovidlo commented on tests/test_generator.py
> +def test_graph_generator_statistics():
А можешь немного погрузить в смысл проверки статистик? Не совсем понимаю почему там сравнение с числами нестрогое?

2023-04-05 11:40 UTC, aPovidlo commented on core/generator.py
> +        for i in range(min_d, max_d + 1):
Кажется, но этот код дублировался в одном примере. Можно его там заменить на эту функцию. При этом также ниже написал про то, как можно обойтись без итерирующего цикла, а генератором.

2023-04-05 11:40 UTC, aPovidlo commented on tests/test_bter.py
> +    for x in range(min_d, max_d + 1):
Эти два цикла можно же вызывать из класса. Не совсем понимаю, зачем дублировать один и тот же код.

2023-04-05 11:40 UTC, aPovidlo commented on core/bter.py
> +        tetta = (
Очень трудно разобрать что тут происходит. Это отступы сбились?

2023-04-05 11:41 UTC, aPovidlo commented on core/generator.py
> +            "\nNumber of classes:{} \nEtta:{} \nro:{} \nRatio of neigbors with same label:{} "
@anpolol можешь ли ты ссылки на код отправить, а то я не обнаружил? Слишком много изменений уже и трудно ориентироваться в новых частях

2023-04-05 11:41 UTC, aPovidlo commented on tutorials/example_generate_graph.py
> +model = Model(
Запустил, все работало. Конечно же, после исправлений с установкой в модулях

2023-04-05 11:42 UTC, aPovidlo commented
Еще обрати внимание на [сообщение ](https://github.com/anpolol/GraphGenerator/pull/9#issuecomment-1497222230) от pep8bot, их тоже желательно исправить

2023-04-05 11:44 UTC, aPovidlo commented
@anpolol Думаю, что, кроме этих двух тестов, дополнительными тестами можно заняться и закрыть в следующем PR. Все-таки этот заточен на рефакторинг кода.

2023-04-05 11:45 UTC, aPovidlo commented on tests/test_bter.py
> +def test_bter_degrees():
@anpolol отписался ниже в комментарии

2023-04-24 13:13 UTC, anpolol commented on core/generator.py
> +            "\nNumber of classes:{} \nEtta:{} \nro:{} \nRatio of neigbors with same label:{} "
https://github.com/anpolol/GraphGenerator/pull/9/files#diff-c06ebde2e457aa7381f452032b7169672e8da223de29cfe9a0480ff27c58679d:~:text=def%20draw_graph(,.graph)

2023-04-24 13:13 UTC, anpolol commented on core/generator.py
> +        nx.draw(self.graph)
тут рисование графа

2023-04-24 13:47 UTC, aPovidlo commented on core/generator.py
> +        nx.draw(self.graph)
А если этот метод взывать до вызова функции `making_graph()`, то он вылетит с ошибкой же? Поэтому лучше обернуть в какую-нибудь конструкцию с проверкой и выводом ошибки, если он пустой.

2023-04-24 14:28 UTC, anpolol commented on tests/test_generator.py
> +def test_graph_generator_statistics():
наш генератор стохастический. И на одних и тех же параметрах выдает чуть различные результаты, условно либо 0.1 либо 0.2, но точно не 0.9
я добавила сейчас сиды в нескольких местах. скажем так этот разброс уменьшился, но все еще не все учлось и результаты чуть отличаются. 
+ прям супер часто результат - это какое-нибудь иррациональное число с которым сложно сравнить точно

2023-04-24 14:33 UTC, anpolol commented on core/generator.py
> +        for i in range(min_d, max_d + 1):
>Можно его там заменить на эту функцию.
Для того чтоб ту функцию вызывать надо объявлять класс Main из generator.py там где этот файл вообще не надо видеть. Может лучше оставить там как есть? ну с исправленной версией без цикла

2023-04-24 14:34 UTC, anpolol commented on tests/test_bter.py
> +    for x in range(min_d, max_d + 1):
так если мне этот класс не надо объявлять. Я тут тестирую класс bter, а не generator
и в классе bter этих функций нет

2023-04-24 14:42 UTC, anpolol commented on core/bter.py
> +        tetta = (
да, black так исправил
но вообще это проcто вот эта формула из статьи по bter
![image](https://user-images.githubusercontent.com/50195080/234030916-7de2906f-2ea4-4f29-a14a-94f9cacd5ac9.png)

2023-04-24 14:45 UTC, anpolol commented on tests/test_bter.py
> +    for x in range(min_d, max_d + 1):
мы эти функции добавили в generator потому что bter должен получать на вход именно такое распределение. А generator по своей сути обертка над bter. но протестировать же надо отдельно файл bter

2023-04-24 14:47 UTC, anpolol commented on core/generator.py
> +        nx.draw(self.graph)
ок

2023-04-24 14:53 UTC, anpolol commented on tests/test_bter.py
> +    model = BTER(
Добавила

2023-04-24 14:53 UTC, anpolol commented on tests/test_bter.py
> +        sum += 1 / (pow(i, 2.0))
исправила, через np.sum

2023-04-24 14:53 UTC, anpolol commented on examples/example_parameters_tuning.py
> +# Here we should set up graph characteristics which constructed graph should have in the following order:
исправила

2023-04-24 14:53 UTC, anpolol commented on core/tuning_parameters.py
> +from hyperopt import STATUS_OK, Trials, atpe, fmin, hp, tpe
тоже добавила

2023-04-24 15:05 UTC, aPovidlo commented on core/bter.py
> +        tetta = (
Думаю, что ее можно разделить на несколько переменных, условно числитель, знаменатель и превратить в более читаемый вид

2023-04-24 15:11 UTC, aPovidlo requested changes
Осталось исправить замечания по PEP8

2023-04-24 15:14 UTC, aPovidlo commented
> Осталось исправить замечания по PEP8

Странно, что он игнорирует увеличение строки до 120. Пока исправь все остальные тогда.

2023-04-25 08:56 UTC, anpolol commented on core/bter.py
> +        tetta = (
исправила

2023-04-26 20:37 UTC, aPovidlo approved these changes

2023-04-27 11:34 UTC, merged